---
builds:
  -
    flags: -tags "static_build"
    ldflags: -w -X main.Version={{.Version}} -X main.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
brews:
  -
    github:
      owner: prologic
      name: homebrew-fbox
    homepage: "https://github.io/prologic/fbox"
    description: |
      fbox is an easy to use and maintain distributed filesystem written in Go
      using Reed Solomon Erasure with FUSE and S3 interfaces and a modern Web UI
signs:
  -
    artifacts: checksum
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
