---
version: "3.8"

services:
  master:
    image: prologic/fbox
    command: -a '{{ GetInterfaceIP "eth0" }}:8000' -d /data
    volumes:
      - fbox:/data
    networks:
      - fbox
      - traefik
    deploy:
      placement:
        constraints:
          - "node.hostname == ${MASTER_NODE:?MASTER_NODE not configured}"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.files.loadbalancer.server.port=8000"
        - "traefik.http.routers.files.rule=Host(`${DOMAIN:?DOMAIN not configured}`)"
      restart_policy:
        condition: on-failure

  node:
    image: prologic/fbox
    command: -a '{{ GetInterfaceIP "eth0" }}:8000' -d /data -m http://fbox_master:8000
    volumes:
      - fbox:/data
    networks:
      - fbox
      - traefik
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == worker"
      restart_policy:
        condition: on-failure

networks:
  fbox:
    driver: overlay
  traefik:
    external: true

volumes:
  fbox:
    driver: local
