---
name: Docker
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build & Publish
        if: (github.event_name == 'schedule' || github.event_name == 'push') && github.repository == 'prologic/fbox'
        env:
          DOCKER_USERNAME: prologic
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          make image PUBLISH=1
